version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # MONGODB_URI: "sua_uri_de_conexao_mongodb_externa"
    env_file:
      - .env # Certifique-se de criar um arquivo .env na raiz do projeto com MONGODB_URI
    # Se preferir não usar um arquivo .env, descomente a linha MONGODB_URI acima
    # e substitua "sua_uri_de_conexao_mongodb_externa" pela sua URI real.

